include:
  template: Dependency-Scanning.gitlab-ci.yml

image: docker:latest

services:
  - docker:dind

build:
  script:
    - docker build -t oxr463/git-syn .
  only:
    - master

pages:
  image: python:alpine
  before_script:
    - apk add gcc
    - pip install -r requirements.txt
  script:
    - mkdocs build -d public
  artifacts:
    paths:
      - public
  only:
    - master
