site_name: Git Synchronize
site_author: Lucas Ramage
site_description: |
  Event-driven git remote repository syncing.

theme:
  name: readthedocs
  custom_dir: doc/theme

docs_dir: doc
site_dir: public

repo_url: https://gitlab.com/oxr463/git-syn.git

nav:
  - Introduction: index.md
  - Manual:
    - Commands:
      - "git-syn": man/git-syn.1.md

copyright: Copyright &copy; 2019-2020 Lucas Ramage.

plugins: 
  - search

